pipeline {
  agent {
    docker {
      image 'node:18.18.0-alpine' // ou 'node:20-alpine' si besoin
      args '-u root:root' // pour éviter les erreurs de permissions
    }
  }

  environment {
    DOCKER_IMAGE_NAME = "meddhia07/growthnest-frontend"
  }

  stages {

    stage('Install Dependencies') {
      steps {
        dir('Frontend') {
          sh '''
            rm -rf node_modules
            npm cache clean --force
            npm install --legacy-peer-deps
          '''
        }
      }
    }

    stage('Check Versions') {
      steps {
        dir('Frontend') {
          sh 'node -v'
          sh 'npx ng version'
        }
      }
    }

    stage('Build Angular App') {
      steps {
        dir('Frontend') {
          sh 'npx ng build --configuration production'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -f Docker/frontend.Dockerfile -t $DOCKER_IMAGE_NAME .'
      }
    }

    stage('Push to DockerHub') {
      steps {
        withDockerRegistry([credentialsId: 'dockerhub', url: '']) {
          sh 'docker push $DOCKER_IMAGE_NAME'
        }
      }
    }
  }
}
