pipeline {
  agent any

  environment {
    DOCKER_IMAGE_NAME = "meddhia07/growthnest-frontend"
  }

  stages {

    stage('Check Versions') {
  steps {
    dir('Frontend') {
      sh 'node -v'
      // Rendre executable les binaires locaux
      sh 'chmod +x node_modules/.bin/ng || true'
      sh 'npx ng version'
    }
  }
}

stage('Install Dependencies') {
  steps {
    dir('Frontend') {
      sh 'npm ci'
    }
  }
}

stage('Build Angular App') {
  steps {
    dir('Frontend') {
      sh 'chmod +x node_modules/.bin/ng || true'
      sh 'npx ng build --configuration production'
    }
  }
}


    stage('Build Docker Image') {
      steps {
        sh 'docker build -f Docker/frontend.Dockerfile -t $DOCKER_IMAGE_NAME .'
      }
    }

    stage('Push to DockerHub') {
      steps {
        withDockerRegistry([credentialsId: 'dockerhub', url: '']) {
          sh 'docker push $DOCKER_IMAGE_NAME'
        }
      }
    }
  }
}
